version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-products
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - drizzle-db
    environment:
      DATABASE_URL: "postgresql://postgres:docker@drizzle-db:5432/postgres"
    networks:
      - app-network

  drizzle-db:
    image: postgres
    restart: always
    container_name: drizzle-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres:/data/postgres
    networks:
      - app-network

volumes:
  postgres:

networks:
  app-network:
    driver: bridge